/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastaseyrinintakibi;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author bahadirsahin
 */
public class Program extends javax.swing.JFrame {
HastaSeyrininTakibi h = new HastaSeyrininTakibi();

    /**
     * Creates new form Program
     */
    

    public void kayitli_hastalari_goster() throws SQLException{
        kayitliHastalarListesi.setModel(new DefaultListModel());
        DefaultListModel model = (DefaultListModel)kayitliHastalarListesi.getModel();
        model.removeAllElements();
        String[] hastalar = h.Kayitli_Hastalar();
        model = (DefaultListModel)kayitliHastalarListesi.getModel();
        for (int i = 0; i < hastalar.length; i++) {
            model.addElement(hastalar[i]);
            
        }
        
    }
    
    public Program() throws SQLException {
        initComponents();
        kadinSayisi.setText(String.valueOf(h.kadin_sayisi()));
        erkekSayisi.setText(String.valueOf(h.erkek_sayisi()));
        kayitli_hastalari_goster();
        kisiSayisi.setText(String.valueOf(h.hasta_adet_al()));
        yasOrtalamasi.setText(String.valueOf(h.hasta_yas_ortalama()));
        this.getContentPane().setPreferredSize(new java.awt.Dimension(250, 130));
        anaPanel.setVisible(false);
        
        doktorBilgileriButonu.setBackground(new java.awt.Color(39, 56, 83));
        
        hastaIslemleriPaneli.setVisible(false);
        hastaIslemleriButonuCizgisi.setVisible(false);
        
        hastaEkleAltPaneli.setVisible(false);
        hastaSilAltPaneli.setVisible(false);
        hastaDuzenleAltPaneli.setVisible(false);
        hastaSorgulaAltPaneli.setVisible(false);
        hastaIslemiAltPaneliBasligi.setText("");
        
        
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        girisPaneli = new javax.swing.JPanel();
        kullaniciAdiBasligi = new javax.swing.JLabel();
        kullaniciAdiVeriGirisi = new javax.swing.JTextField();
        sifreBasligi = new javax.swing.JLabel();
        girisButonu = new javax.swing.JButton();
        sifreVeriGirisi = new javax.swing.JPasswordField();
        anaPanel = new javax.swing.JPanel();
        navigasyonPaneli = new javax.swing.JPanel();
        doktorBilgileriButonu = new javax.swing.JButton();
        doktorBilgileriButonuCizgisi = new javax.swing.JLabel();
        hastaIslemleriButonu = new javax.swing.JButton();
        hastaIslemleriButonuCizgisi = new javax.swing.JLabel();
        hastaIslemleriPaneli = new javax.swing.JPanel();
        kayitliHastalarAltPaneliBasligi = new javax.swing.JLabel();
        kayitliHastalarAltPaneli = new javax.swing.JScrollPane();
        kayitliHastalarListesi = new javax.swing.JList<>();
        yasOrtalamasiAltPaneliBasligi = new javax.swing.JLabel();
        yasOrtalamasiAltPaneli = new javax.swing.JPanel();
        yasOrtalamasi = new javax.swing.JLabel();
        hastaIslemleriAltPaneliBasligi = new javax.swing.JLabel();
        hastaIslemleriAltPaneli = new javax.swing.JPanel();
        hastaSilButonu = new javax.swing.JButton();
        hastaDuzenleButonu = new javax.swing.JButton();
        hastaSorgulaButonu = new javax.swing.JButton();
        hastaEkleButonu = new javax.swing.JButton();
        hastaIslemiAltPaneliBasligi = new javax.swing.JLabel();
        hastaDuzenleAltPaneli = new javax.swing.JPanel();
        hastaninTCKimligiDuzenleBasligi = new javax.swing.JLabel();
        hastaninAdiSoyadiDuzenleBasligi = new javax.swing.JLabel();
        hastaninDogumTarihiDuzenleBasligi = new javax.swing.JLabel();
        hastaninCinsiyetiDuzenleBasligi = new javax.swing.JLabel();
        hastaninHastaligiDuzenleBasligi = new javax.swing.JLabel();
        hastaninDurumuDuzenleBasligi = new javax.swing.JLabel();
        hastaninTCKimligiDuzenleVeriGirisi = new javax.swing.JTextField();
        hastaninAdiSoyadiDuzenleVeriGirisi = new javax.swing.JTextField();
        hastaninDogumTarihiDuzenleVeriGirisi = new javax.swing.JTextField();
        hastaninCinsiyetiDuzenleVeriGirisi = new javax.swing.JTextField();
        hastaninHastaligiDuzenleVeriGirisi = new javax.swing.JTextField();
        hastaninDurumuDuzenleVeriGirisi = new javax.swing.JTextField();
        hastayiKaydetButonu = new javax.swing.JButton();
        hastaSorgulaAltPaneli = new javax.swing.JPanel();
        hastaninTCKimligiSorgulaBasligi = new javax.swing.JLabel();
        hastaninTCKimligiSorgulaVeriGirisi = new javax.swing.JTextField();
        hastayiSorgulaBuyonu = new javax.swing.JButton();
        hastaSilAltPaneli = new javax.swing.JPanel();
        hastaninTCKimligiSilBasligi = new javax.swing.JLabel();
        hastaninTCKimligiSilVeriGirisi = new javax.swing.JTextField();
        hastayiSilButonu = new javax.swing.JButton();
        hastaEkleAltPaneli = new javax.swing.JPanel();
        hastaninTCKimligiBasligi = new javax.swing.JLabel();
        hastaninAdiSoyadiBasligi = new javax.swing.JLabel();
        hastaninDogumTarihiBasligi = new javax.swing.JLabel();
        hastaninCinsiyetiBasligi = new javax.swing.JLabel();
        hastaninHastaligiBasligi = new javax.swing.JLabel();
        hastaninDurumuBasligi = new javax.swing.JLabel();
        hastaninTCKimligiVeriGirisi = new javax.swing.JTextField();
        hastaninAdiSoyadiVeriGirisi = new javax.swing.JTextField();
        hastaninDogumTarihiVeriGirisi = new javax.swing.JTextField();
        hastaninCinsiyetiVeriGirisi = new javax.swing.JTextField();
        hastaninHastaligiVeriGirisi = new javax.swing.JTextField();
        hastaninDurumuVeriGirisi = new javax.swing.JTextField();
        hastayiEkleButonu = new javax.swing.JButton();
        kisiSayisi = new javax.swing.JLabel();
        kadinSayisi = new javax.swing.JLabel();
        kadinSayisi1 = new javax.swing.JLabel();
        erkekSayisi1 = new javax.swing.JLabel();
        erkekSayisi = new javax.swing.JLabel();
        doktorBilgileriPaneli = new javax.swing.JPanel();
        doktorBilgileriAltPaneliBasligi = new javax.swing.JLabel();
        doktorBilgileriAltPaneli = new javax.swing.JPanel();
        doktorAdiBasligi = new javax.swing.JLabel();
        doktorAdiYazisi = new javax.swing.JLabel();
        doktorYasiBasligi = new javax.swing.JLabel();
        doktorYasiYazisi = new javax.swing.JLabel();
        doktorCinsiyetiBasligi = new javax.swing.JLabel();
        doktorCinsiyetiYazisi = new javax.swing.JLabel();
        doktorKimligiBasligi = new javax.swing.JLabel();
        doktorKimligiYazisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hasta Seyrinin Takibi");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/simge.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        girisPaneli.setBackground(new java.awt.Color(239, 239, 239));
        girisPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kullaniciAdiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kullaniciAdiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        kullaniciAdiBasligi.setText("KULLANICI ADINIZ");
        girisPaneli.add(kullaniciAdiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 10));

        kullaniciAdiVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        kullaniciAdiVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kullaniciAdiVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        kullaniciAdiVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        kullaniciAdiVeriGirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciAdiVeriGirisiActionPerformed(evt);
            }
        });
        girisPaneli.add(kullaniciAdiVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 20));

        sifreBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        sifreBasligi.setForeground(new java.awt.Color(66, 66, 66));
        sifreBasligi.setText("ŞİFRENİZ");
        girisPaneli.add(sifreBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 10));

        girisButonu.setBackground(new java.awt.Color(207, 207, 207));
        girisButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        girisButonu.setForeground(new java.awt.Color(27, 27, 27));
        girisButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/giris_yap.png"))); // NOI18N
        girisButonu.setText("Giriş Yap");
        girisButonu.setContentAreaFilled(false);
        girisButonu.setOpaque(true);
        girisButonu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                girisButonuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                girisButonuMouseEntered(evt);
            }
        });
        girisButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButonuActionPerformed(evt);
            }
        });
        girisPaneli.add(girisButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        sifreVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        sifreVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        sifreVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        girisPaneli.add(sifreVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 20));

        getContentPane().add(girisPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 130));

        anaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigasyonPaneli.setBackground(new java.awt.Color(24, 34, 56));
        navigasyonPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doktorBilgileriButonu.setBackground(new java.awt.Color(24, 34, 56));
        doktorBilgileriButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        doktorBilgileriButonu.setForeground(new java.awt.Color(239, 239, 239));
        doktorBilgileriButonu.setContentAreaFilled(false);
        doktorBilgileriButonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        doktorBilgileriButonu.setLabel("Doktor Bilgileri");
        doktorBilgileriButonu.setOpaque(true);
        doktorBilgileriButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorBilgileriButonuActionPerformed(evt);
            }
        });
        navigasyonPaneli.add(doktorBilgileriButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 50, 117, 30));

        doktorBilgileriButonuCizgisi.setBackground(new java.awt.Color(239, 239, 239));
        doktorBilgileriButonuCizgisi.setOpaque(true);
        navigasyonPaneli.add(doktorBilgileriButonuCizgisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 3, 30));

        hastaIslemleriButonu.setBackground(new java.awt.Color(24, 34, 56));
        hastaIslemleriButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaIslemleriButonu.setForeground(new java.awt.Color(239, 239, 239));
        hastaIslemleriButonu.setContentAreaFilled(false);
        hastaIslemleriButonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hastaIslemleriButonu.setLabel("Hasta İşlemleri");
        hastaIslemleriButonu.setOpaque(true);
        hastaIslemleriButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaIslemleriButonuActionPerformed(evt);
            }
        });
        navigasyonPaneli.add(hastaIslemleriButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 80, 117, 30));

        hastaIslemleriButonuCizgisi.setBackground(new java.awt.Color(239, 239, 239));
        hastaIslemleriButonuCizgisi.setOpaque(true);
        navigasyonPaneli.add(hastaIslemleriButonuCizgisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 3, 30));

        anaPanel.add(navigasyonPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 360));

        hastaIslemleriPaneli.setBackground(new java.awt.Color(224, 224, 224));
        hastaIslemleriPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kayitliHastalarAltPaneliBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kayitliHastalarAltPaneliBasligi.setForeground(new java.awt.Color(117, 117, 117));
        kayitliHastalarAltPaneliBasligi.setText("KAYITLI HASTALAR");
        hastaIslemleriPaneli.add(kayitliHastalarAltPaneliBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 10));

        kayitliHastalarAltPaneli.setBackground(new java.awt.Color(239, 239, 239));
        kayitliHastalarAltPaneli.setBorder(null);

        kayitliHastalarAltPaneli.setViewportView(kayitliHastalarListesi);

        hastaIslemleriPaneli.add(kayitliHastalarAltPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 70));

        yasOrtalamasiAltPaneliBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        yasOrtalamasiAltPaneliBasligi.setForeground(new java.awt.Color(117, 117, 117));
        yasOrtalamasiAltPaneliBasligi.setText("YAŞ ORTALAMASI");
        hastaIslemleriPaneli.add(yasOrtalamasiAltPaneliBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 10));

        yasOrtalamasiAltPaneli.setBackground(new java.awt.Color(239, 239, 239));
        yasOrtalamasiAltPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        yasOrtalamasiAltPaneli.add(yasOrtalamasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 20));

        hastaIslemleriPaneli.add(yasOrtalamasiAltPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 20));

        hastaIslemleriAltPaneliBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaIslemleriAltPaneliBasligi.setForeground(new java.awt.Color(117, 117, 117));
        hastaIslemleriAltPaneliBasligi.setText("HASTA İŞLEMLERİ");
        hastaIslemleriPaneli.add(hastaIslemleriAltPaneliBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 10));

        hastaIslemleriAltPaneli.setBackground(new java.awt.Color(239, 239, 239));
        hastaIslemleriAltPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hastaSilButonu.setBackground(new java.awt.Color(207, 207, 207));
        hastaSilButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaSilButonu.setForeground(new java.awt.Color(27, 27, 27));
        hastaSilButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/hasta_sil.png"))); // NOI18N
        hastaSilButonu.setText("Hasta Sil");
        hastaSilButonu.setContentAreaFilled(false);
        hastaSilButonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hastaSilButonu.setOpaque(true);
        hastaSilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaSilButonuActionPerformed(evt);
            }
        });
        hastaIslemleriAltPaneli.add(hastaSilButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 30));

        hastaDuzenleButonu.setBackground(new java.awt.Color(207, 207, 207));
        hastaDuzenleButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaDuzenleButonu.setForeground(new java.awt.Color(27, 27, 27));
        hastaDuzenleButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/hasta_duzenle.png"))); // NOI18N
        hastaDuzenleButonu.setText("Hasta Düzenle");
        hastaDuzenleButonu.setContentAreaFilled(false);
        hastaDuzenleButonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hastaDuzenleButonu.setOpaque(true);
        hastaDuzenleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaDuzenleButonuActionPerformed(evt);
            }
        });
        hastaIslemleriAltPaneli.add(hastaDuzenleButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        hastaSorgulaButonu.setBackground(new java.awt.Color(207, 207, 207));
        hastaSorgulaButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaSorgulaButonu.setForeground(new java.awt.Color(27, 27, 27));
        hastaSorgulaButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/hasta_sorgula.png"))); // NOI18N
        hastaSorgulaButonu.setText("Hasta Sorgula");
        hastaSorgulaButonu.setContentAreaFilled(false);
        hastaSorgulaButonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hastaSorgulaButonu.setOpaque(true);
        hastaSorgulaButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaSorgulaButonuActionPerformed(evt);
            }
        });
        hastaIslemleriAltPaneli.add(hastaSorgulaButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        hastaEkleButonu.setBackground(new java.awt.Color(207, 207, 207));
        hastaEkleButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaEkleButonu.setForeground(new java.awt.Color(27, 27, 27));
        hastaEkleButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/hasta_ekle.png"))); // NOI18N
        hastaEkleButonu.setText("Hasta Ekle");
        hastaEkleButonu.setContentAreaFilled(false);
        hastaEkleButonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hastaEkleButonu.setOpaque(true);
        hastaEkleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaEkleButonuActionPerformed(evt);
            }
        });
        hastaIslemleriAltPaneli.add(hastaEkleButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        hastaIslemleriPaneli.add(hastaIslemleriAltPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, 170));

        hastaIslemiAltPaneliBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaIslemiAltPaneliBasligi.setForeground(new java.awt.Color(117, 117, 117));
        hastaIslemiAltPaneliBasligi.setText("HASTA EKLE");
        hastaIslemleriPaneli.add(hastaIslemiAltPaneliBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 340, 10));

        hastaDuzenleAltPaneli.setBackground(new java.awt.Color(239, 239, 239));
        hastaDuzenleAltPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hastaninTCKimligiDuzenleBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninTCKimligiDuzenleBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninTCKimligiDuzenleBasligi.setText("HASTANIN TC KİMLİĞİ");
        hastaDuzenleAltPaneli.add(hastaninTCKimligiDuzenleBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 10));

        hastaninAdiSoyadiDuzenleBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninAdiSoyadiDuzenleBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninAdiSoyadiDuzenleBasligi.setText("HASTANIN YENİ ADI SOYADI");
        hastaDuzenleAltPaneli.add(hastaninAdiSoyadiDuzenleBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 10));

        hastaninDogumTarihiDuzenleBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninDogumTarihiDuzenleBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninDogumTarihiDuzenleBasligi.setText("HASTANIN YENİ DOĞUM TARİHİ");
        hastaDuzenleAltPaneli.add(hastaninDogumTarihiDuzenleBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 320, 10));

        hastaninCinsiyetiDuzenleBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninCinsiyetiDuzenleBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninCinsiyetiDuzenleBasligi.setText("HASTANIN YENİ CİNSİYETİ");
        hastaDuzenleAltPaneli.add(hastaninCinsiyetiDuzenleBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 320, 10));

        hastaninHastaligiDuzenleBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninHastaligiDuzenleBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninHastaligiDuzenleBasligi.setText("HASTANIN YENİ HASTALIĞI");
        hastaninHastaligiDuzenleBasligi.setToolTipText("");
        hastaDuzenleAltPaneli.add(hastaninHastaligiDuzenleBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 320, 10));

        hastaninDurumuDuzenleBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninDurumuDuzenleBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninDurumuDuzenleBasligi.setText("HASTANIN YENİ DURUMU");
        hastaninDurumuDuzenleBasligi.setToolTipText("");
        hastaDuzenleAltPaneli.add(hastaninDurumuDuzenleBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 320, 10));

        hastaninTCKimligiDuzenleVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninTCKimligiDuzenleVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninTCKimligiDuzenleVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninTCKimligiDuzenleVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaninTCKimligiDuzenleVeriGirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaninTCKimligiDuzenleVeriGirisiActionPerformed(evt);
            }
        });
        hastaDuzenleAltPaneli.add(hastaninTCKimligiDuzenleVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 20));

        hastaninAdiSoyadiDuzenleVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninAdiSoyadiDuzenleVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninAdiSoyadiDuzenleVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninAdiSoyadiDuzenleVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaDuzenleAltPaneli.add(hastaninAdiSoyadiDuzenleVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 320, 20));

        hastaninDogumTarihiDuzenleVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninDogumTarihiDuzenleVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninDogumTarihiDuzenleVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninDogumTarihiDuzenleVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaDuzenleAltPaneli.add(hastaninDogumTarihiDuzenleVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 320, 20));

        hastaninCinsiyetiDuzenleVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninCinsiyetiDuzenleVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninCinsiyetiDuzenleVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninCinsiyetiDuzenleVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaDuzenleAltPaneli.add(hastaninCinsiyetiDuzenleVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 320, 20));

        hastaninHastaligiDuzenleVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninHastaligiDuzenleVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninHastaligiDuzenleVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninHastaligiDuzenleVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaDuzenleAltPaneli.add(hastaninHastaligiDuzenleVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 320, 20));

        hastaninDurumuDuzenleVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninDurumuDuzenleVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninDurumuDuzenleVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninDurumuDuzenleVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaDuzenleAltPaneli.add(hastaninDurumuDuzenleVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 320, 20));

        hastayiKaydetButonu.setBackground(new java.awt.Color(207, 207, 207));
        hastayiKaydetButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastayiKaydetButonu.setForeground(new java.awt.Color(27, 27, 27));
        hastayiKaydetButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/kaydet.png"))); // NOI18N
        hastayiKaydetButonu.setText("Hastayı Kaydet");
        hastayiKaydetButonu.setContentAreaFilled(false);
        hastayiKaydetButonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hastayiKaydetButonu.setOpaque(true);
        hastayiKaydetButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastayiKaydetButonuActionPerformed(evt);
            }
        });
        hastaDuzenleAltPaneli.add(hastayiKaydetButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 130, 30));

        hastaIslemleriPaneli.add(hastaDuzenleAltPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 340, 320));

        hastaSorgulaAltPaneli.setBackground(new java.awt.Color(239, 239, 239));
        hastaSorgulaAltPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hastaninTCKimligiSorgulaBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninTCKimligiSorgulaBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninTCKimligiSorgulaBasligi.setText("HASTANIN TC KİMLİĞİ");
        hastaSorgulaAltPaneli.add(hastaninTCKimligiSorgulaBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 10));

        hastaninTCKimligiSorgulaVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninTCKimligiSorgulaVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninTCKimligiSorgulaVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninTCKimligiSorgulaVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaSorgulaAltPaneli.add(hastaninTCKimligiSorgulaVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 20));

        hastayiSorgulaBuyonu.setBackground(new java.awt.Color(207, 207, 207));
        hastayiSorgulaBuyonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastayiSorgulaBuyonu.setForeground(new java.awt.Color(27, 27, 27));
        hastayiSorgulaBuyonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/bul.png"))); // NOI18N
        hastayiSorgulaBuyonu.setText("Hastayı Sorgula");
        hastayiSorgulaBuyonu.setContentAreaFilled(false);
        hastayiSorgulaBuyonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hastayiSorgulaBuyonu.setOpaque(true);
        hastayiSorgulaBuyonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastayiSorgulaBuyonuActionPerformed(evt);
            }
        });
        hastaSorgulaAltPaneli.add(hastayiSorgulaBuyonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 140, 30));

        hastaIslemleriPaneli.add(hastaSorgulaAltPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 340, 320));

        hastaSilAltPaneli.setBackground(new java.awt.Color(239, 239, 239));
        hastaSilAltPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hastaninTCKimligiSilBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninTCKimligiSilBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninTCKimligiSilBasligi.setText("HASTANIN TC KİMLİĞİ");
        hastaSilAltPaneli.add(hastaninTCKimligiSilBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 10));

        hastaninTCKimligiSilVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninTCKimligiSilVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninTCKimligiSilVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninTCKimligiSilVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaSilAltPaneli.add(hastaninTCKimligiSilVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 20));

        hastayiSilButonu.setBackground(new java.awt.Color(207, 207, 207));
        hastayiSilButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastayiSilButonu.setForeground(new java.awt.Color(27, 27, 27));
        hastayiSilButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/sil.png"))); // NOI18N
        hastayiSilButonu.setText("Hastayı Sil");
        hastayiSilButonu.setContentAreaFilled(false);
        hastayiSilButonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hastayiSilButonu.setOpaque(true);
        hastayiSilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastayiSilButonuActionPerformed(evt);
            }
        });
        hastaSilAltPaneli.add(hastayiSilButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 110, 30));

        hastaIslemleriPaneli.add(hastaSilAltPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 340, 320));

        hastaEkleAltPaneli.setBackground(new java.awt.Color(239, 239, 239));
        hastaEkleAltPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hastaninTCKimligiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninTCKimligiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninTCKimligiBasligi.setText("HASTANIN TC KİMLİĞİ");
        hastaEkleAltPaneli.add(hastaninTCKimligiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 10));

        hastaninAdiSoyadiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninAdiSoyadiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninAdiSoyadiBasligi.setText("HASTANIN ADI SOYADI");
        hastaEkleAltPaneli.add(hastaninAdiSoyadiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 10));

        hastaninDogumTarihiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninDogumTarihiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninDogumTarihiBasligi.setText("HASTANIN DOĞUM TARİHİ");
        hastaEkleAltPaneli.add(hastaninDogumTarihiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 320, 10));

        hastaninCinsiyetiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninCinsiyetiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninCinsiyetiBasligi.setText("HASTANIN CİNSİYETİ");
        hastaEkleAltPaneli.add(hastaninCinsiyetiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 320, 10));

        hastaninHastaligiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninHastaligiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninHastaligiBasligi.setText("HASTANIN HASTALIĞI");
        hastaninHastaligiBasligi.setToolTipText("");
        hastaEkleAltPaneli.add(hastaninHastaligiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 320, 10));

        hastaninDurumuBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        hastaninDurumuBasligi.setForeground(new java.awt.Color(66, 66, 66));
        hastaninDurumuBasligi.setText("HASTANIN DURUMU");
        hastaninDurumuBasligi.setToolTipText("");
        hastaEkleAltPaneli.add(hastaninDurumuBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 320, 10));

        hastaninTCKimligiVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninTCKimligiVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninTCKimligiVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninTCKimligiVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaEkleAltPaneli.add(hastaninTCKimligiVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 20));

        hastaninAdiSoyadiVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninAdiSoyadiVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninAdiSoyadiVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninAdiSoyadiVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaEkleAltPaneli.add(hastaninAdiSoyadiVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 320, 20));

        hastaninDogumTarihiVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninDogumTarihiVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninDogumTarihiVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninDogumTarihiVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaEkleAltPaneli.add(hastaninDogumTarihiVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 320, 20));

        hastaninCinsiyetiVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninCinsiyetiVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninCinsiyetiVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninCinsiyetiVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaEkleAltPaneli.add(hastaninCinsiyetiVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 320, 20));

        hastaninHastaligiVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninHastaligiVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninHastaligiVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninHastaligiVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaEkleAltPaneli.add(hastaninHastaligiVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 320, 20));

        hastaninDurumuVeriGirisi.setBackground(new java.awt.Color(224, 224, 224));
        hastaninDurumuVeriGirisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastaninDurumuVeriGirisi.setForeground(new java.awt.Color(27, 27, 27));
        hastaninDurumuVeriGirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207), 2));
        hastaEkleAltPaneli.add(hastaninDurumuVeriGirisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 320, 20));

        hastayiEkleButonu.setBackground(new java.awt.Color(207, 207, 207));
        hastayiEkleButonu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hastayiEkleButonu.setForeground(new java.awt.Color(27, 27, 27));
        hastayiEkleButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaseyrinintakibi/kaynak/ekle.png"))); // NOI18N
        hastayiEkleButonu.setText("Hastayı Ekle");
        hastayiEkleButonu.setContentAreaFilled(false);
        hastayiEkleButonu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hastayiEkleButonu.setOpaque(true);
        hastayiEkleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastayiEkleButonuActionPerformed(evt);
            }
        });
        hastaEkleAltPaneli.add(hastayiEkleButonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 120, 30));

        hastaIslemleriPaneli.add(hastaEkleAltPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 340, 320));

        kisiSayisi.setFont(new java.awt.Font("Seravek", 0, 13)); // NOI18N
        kisiSayisi.setForeground(new java.awt.Color(51, 51, 51));
        hastaIslemleriPaneli.add(kisiSayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 4, 60, 20));

        kadinSayisi.setFont(new java.awt.Font("Seravek", 0, 11)); // NOI18N
        kadinSayisi.setForeground(new java.awt.Color(51, 51, 51));
        hastaIslemleriPaneli.add(kadinSayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 105, 20, 20));

        kadinSayisi1.setFont(new java.awt.Font("Seravek", 0, 11)); // NOI18N
        kadinSayisi1.setForeground(new java.awt.Color(51, 51, 51));
        kadinSayisi1.setText("K:");
        kadinSayisi1.setPreferredSize(new java.awt.Dimension(8, 13));
        hastaIslemleriPaneli.add(kadinSayisi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 105, 20, 20));

        erkekSayisi1.setFont(new java.awt.Font("Seravek", 0, 11)); // NOI18N
        erkekSayisi1.setForeground(new java.awt.Color(51, 51, 51));
        erkekSayisi1.setText("E:");
        hastaIslemleriPaneli.add(erkekSayisi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 105, 20, 20));

        erkekSayisi.setFont(new java.awt.Font("Seravek", 0, 11)); // NOI18N
        erkekSayisi.setForeground(new java.awt.Color(51, 51, 51));
        hastaIslemleriPaneli.add(erkekSayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 105, 20, 20));

        anaPanel.add(hastaIslemleriPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 520, 360));

        doktorBilgileriPaneli.setBackground(new java.awt.Color(224, 224, 224));
        doktorBilgileriPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doktorBilgileriAltPaneliBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        doktorBilgileriAltPaneliBasligi.setForeground(new java.awt.Color(117, 117, 117));
        doktorBilgileriAltPaneliBasligi.setText("DOKTOR BİLGİLERİ");
        doktorBilgileriPaneli.add(doktorBilgileriAltPaneliBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 10));

        doktorBilgileriAltPaneli.setBackground(new java.awt.Color(239, 239, 239));
        doktorBilgileriAltPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doktorAdiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        doktorAdiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        doktorAdiBasligi.setText("DOKTOR ADI");
        doktorBilgileriAltPaneli.add(doktorAdiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 10));

        doktorAdiYazisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        doktorAdiYazisi.setForeground(new java.awt.Color(27, 27, 27));
        doktorAdiYazisi.setText("Tarık Acaroğlu");
        doktorBilgileriAltPaneli.add(doktorAdiYazisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 480, 20));

        doktorYasiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        doktorYasiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        doktorYasiBasligi.setText("DOKTOR YAŞI");
        doktorBilgileriAltPaneli.add(doktorYasiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 10));

        doktorYasiYazisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        doktorYasiYazisi.setForeground(new java.awt.Color(27, 27, 27));
        doktorYasiYazisi.setText("47");
        doktorBilgileriAltPaneli.add(doktorYasiYazisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 480, 20));

        doktorCinsiyetiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        doktorCinsiyetiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        doktorCinsiyetiBasligi.setText("DOKTOR CİNSİYETİ");
        doktorBilgileriAltPaneli.add(doktorCinsiyetiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 480, 10));

        doktorCinsiyetiYazisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        doktorCinsiyetiYazisi.setForeground(new java.awt.Color(27, 27, 27));
        doktorCinsiyetiYazisi.setText("Erkek");
        doktorBilgileriAltPaneli.add(doktorCinsiyetiYazisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 480, 20));

        doktorKimligiBasligi.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        doktorKimligiBasligi.setForeground(new java.awt.Color(66, 66, 66));
        doktorKimligiBasligi.setText("DOKTOR KİMLİĞİ");
        doktorBilgileriAltPaneli.add(doktorKimligiBasligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 480, 10));

        doktorKimligiYazisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        doktorKimligiYazisi.setForeground(new java.awt.Color(27, 27, 27));
        doktorKimligiYazisi.setText("42587637536");
        doktorKimligiYazisi.setToolTipText("");
        doktorBilgileriAltPaneli.add(doktorKimligiYazisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 480, 20));

        doktorBilgileriPaneli.add(doktorBilgileriAltPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 170));

        anaPanel.add(doktorBilgileriPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 520, 360));

        getContentPane().add(anaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doktorBilgileriButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorBilgileriButonuActionPerformed
        // TODO add your handling code here:
        doktorBilgileriPaneli.setVisible(true);
        doktorBilgileriButonuCizgisi.setVisible(true);
        doktorBilgileriButonu.setBackground(new java.awt.Color(39, 56, 83));
        
        hastaIslemleriPaneli.setVisible(false);
        hastaIslemleriButonuCizgisi.setVisible(false);
        hastaIslemleriButonu.setBackground(new java.awt.Color(24, 34, 56));
    }//GEN-LAST:event_doktorBilgileriButonuActionPerformed

    private void hastaIslemleriButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaIslemleriButonuActionPerformed
        // TODO add your handling code here:
        hastaIslemleriPaneli.setVisible(true);
        hastaIslemleriButonuCizgisi.setVisible(true);
        hastaIslemleriButonu.setBackground(new java.awt.Color(39, 56, 83));
        
        doktorBilgileriPaneli.setVisible(false);
        doktorBilgileriButonuCizgisi.setVisible(false);
        doktorBilgileriButonu.setBackground(new java.awt.Color(24, 34, 56));
    }//GEN-LAST:event_hastaIslemleriButonuActionPerformed

    private void hastaEkleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaEkleButonuActionPerformed
        // TODO add your handling code here:
        hastaEkleAltPaneli.setVisible(true);
        hastaSilAltPaneli.setVisible(false);
        hastaDuzenleAltPaneli.setVisible(false);
        hastaSorgulaAltPaneli.setVisible(false);
        hastaIslemiAltPaneliBasligi.setText("HASTA EKLE");
    }//GEN-LAST:event_hastaEkleButonuActionPerformed

    private void hastaSilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaSilButonuActionPerformed
        // TODO add your handling code here:
        hastaEkleAltPaneli.setVisible(false);
        hastaSilAltPaneli.setVisible(true);
        hastaDuzenleAltPaneli.setVisible(false);
        hastaSorgulaAltPaneli.setVisible(false);
        hastaIslemiAltPaneliBasligi.setText("HASTA SİL");
    }//GEN-LAST:event_hastaSilButonuActionPerformed

    private void hastaDuzenleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaDuzenleButonuActionPerformed
        // TODO add your handling code here:
        hastaEkleAltPaneli.setVisible(false);
        hastaSilAltPaneli.setVisible(false);
        hastaDuzenleAltPaneli.setVisible(true);
        hastaSorgulaAltPaneli.setVisible(false);
        hastaIslemiAltPaneliBasligi.setText("HASTA DÜZENLE");
    }//GEN-LAST:event_hastaDuzenleButonuActionPerformed

    private void hastaSorgulaButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaSorgulaButonuActionPerformed
        // TODO add your handling code here:
        hastaEkleAltPaneli.setVisible(false);
        hastaSilAltPaneli.setVisible(false);
        hastaDuzenleAltPaneli.setVisible(false);
        hastaSorgulaAltPaneli.setVisible(true);
        hastaIslemiAltPaneliBasligi.setText("HASTA SORGULA");
    }//GEN-LAST:event_hastaSorgulaButonuActionPerformed

    private void girisButonuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisButonuMouseEntered
        // TODO add your handling code here:
        girisButonu.setBackground(new java.awt.Color(224, 224, 224));
    }//GEN-LAST:event_girisButonuMouseEntered

    private void girisButonuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisButonuMouseExited
        // TODO add your handling code here:
        girisButonu.setBackground(new java.awt.Color(207, 207, 207));
    }//GEN-LAST:event_girisButonuMouseExited

    private void girisButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButonuActionPerformed
        // TODO add your handling code here:
        String kullanici_adi = kullaniciAdiVeriGirisi.getText();
        String sifre = String.valueOf(sifreVeriGirisi.getPassword());
    try {
        Boolean giris = h.kullanici_girisi(kullanici_adi, sifre);
        if (giris){
            girisPaneli.setVisible(false);
            anaPanel.setVisible(true);
            this.getContentPane().setPreferredSize(new java.awt.Dimension(640, 360));
            this.pack();
        }
        else{
            JOptionPane.showMessageDialog(this, "Hatalı giriş yaptınız.");
        }
    } catch (SQLException ex) {
        Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_girisButonuActionPerformed

    private void hastayiKaydetButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastayiKaydetButonuActionPerformed
        // TODO add your handling code here:
        String TC_duzenle = hastaninTCKimligiDuzenleVeriGirisi.getText();
        String isim_duzenle = hastaninAdiSoyadiDuzenleVeriGirisi.getText();
        int dogum_tarihi_duzenle = Integer.valueOf(hastaninDogumTarihiDuzenleVeriGirisi.getText());
        String cinsiyet_duzenle = hastaninCinsiyetiDuzenleVeriGirisi.getText();
        String hastalik_duzenle = hastaninHastaligiDuzenleVeriGirisi.getText();
        String durum_duzenle = hastaninDurumuDuzenleVeriGirisi.getText();
    try {
        h.hasta_duzenle(TC_duzenle, isim_duzenle, dogum_tarihi_duzenle, cinsiyet_duzenle, hastalik_duzenle, durum_duzenle);
        kayitli_hastalari_goster();
        yasOrtalamasi.setText(String.valueOf(h.hasta_yas_ortalama()));
        kisiSayisi.setText(String.valueOf(h.hasta_adet_al()));
        kadinSayisi.setText(String.valueOf(h.kadin_sayisi()));
        erkekSayisi.setText(String.valueOf(h.erkek_sayisi()));
        JOptionPane.showMessageDialog(this, "Hastanın bilgileri başarıyla değiştirildi.");
    } catch (SQLException ex) {
        Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
    }
    hastaninTCKimligiDuzenleVeriGirisi.setText("");
    hastaninAdiSoyadiDuzenleVeriGirisi.setText("");
    hastaninDogumTarihiDuzenleVeriGirisi.setText("");
    hastaninCinsiyetiDuzenleVeriGirisi.setText("");
    hastaninHastaligiDuzenleVeriGirisi.setText("");
    hastaninDurumuDuzenleVeriGirisi.setText("");
        
    }//GEN-LAST:event_hastayiKaydetButonuActionPerformed

    private void hastaninTCKimligiDuzenleVeriGirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaninTCKimligiDuzenleVeriGirisiActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_hastaninTCKimligiDuzenleVeriGirisiActionPerformed

    private void hastayiEkleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastayiEkleButonuActionPerformed
        // TODO add your handling code here:
        String TC_ekle = hastaninTCKimligiVeriGirisi.getText();
        String isim_ekle = hastaninAdiSoyadiVeriGirisi.getText();
        int dogum_tarihi_ekle = Integer.valueOf(hastaninDogumTarihiVeriGirisi.getText());
        String cinsiyet_ekle = hastaninCinsiyetiVeriGirisi.getText();
        String hastalik_ekle = hastaninHastaligiVeriGirisi.getText();
        String durum_ekle = hastaninDurumuVeriGirisi.getText();
        
        try {
            h.Hastayi_Ekle(TC_ekle, isim_ekle, dogum_tarihi_ekle, cinsiyet_ekle, hastalik_ekle, durum_ekle);
            kayitli_hastalari_goster();
            yasOrtalamasi.setText(String.valueOf(h.hasta_yas_ortalama()));
            kisiSayisi.setText(String.valueOf(h.hasta_adet_al()));
            kadinSayisi.setText(String.valueOf(h.kadin_sayisi()));
            erkekSayisi.setText(String.valueOf(h.erkek_sayisi()));
            JOptionPane.showMessageDialog(this, "Hasta başarıyla eklendi.");
        } catch (SQLException ex) {
            Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
        }
        hastaninTCKimligiVeriGirisi.setText("");
        hastaninAdiSoyadiVeriGirisi.setText("");
        hastaninDogumTarihiVeriGirisi.setText("");
        hastaninCinsiyetiVeriGirisi.setText("");
        hastaninHastaligiVeriGirisi.setText("");
        hastaninDurumuVeriGirisi.setText("");
    }//GEN-LAST:event_hastayiEkleButonuActionPerformed

    private void kullaniciAdiVeriGirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciAdiVeriGirisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciAdiVeriGirisiActionPerformed

    private void hastayiSilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastayiSilButonuActionPerformed
        // TODO add your handling code here:
        String TC_sil = hastaninTCKimligiSilVeriGirisi.getText();
    try {
        if(h.Hastayi_Sil(TC_sil)){
            kayitli_hastalari_goster();
            yasOrtalamasi.setText(String.valueOf(h.hasta_yas_ortalama()));
            kisiSayisi.setText(String.valueOf(h.hasta_adet_al()));
            kadinSayisi.setText(String.valueOf(h.kadin_sayisi()));
            erkekSayisi.setText(String.valueOf(h.erkek_sayisi()));
            JOptionPane.showMessageDialog(this, "Hasta başarıyla silindi.");
        }
        else{
            JOptionPane.showMessageDialog(this, "Bu TC kimlik numarasına sahip hasta bulunmamaktadır.");
        }
            
    } catch (SQLException ex) {
        Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
    }
    hastaninTCKimligiSilVeriGirisi.setText("");
        
    }//GEN-LAST:event_hastayiSilButonuActionPerformed

    private void hastayiSorgulaBuyonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastayiSorgulaBuyonuActionPerformed
        // TODO add your handling code here:
        String TC_sorgula = hastaninTCKimligiSorgulaVeriGirisi.getText();
    try {
        String Mesaj = h.hasta_goster(TC_sorgula);
        hastaninTCKimligiSorgulaVeriGirisi.setText("");
        JOptionPane.showMessageDialog(this, Mesaj, "Hasta Sorgulama", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException ex) {
        Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_hastayiSorgulaBuyonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Program().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anaPanel;
    private javax.swing.JLabel doktorAdiBasligi;
    private javax.swing.JLabel doktorAdiYazisi;
    private javax.swing.JPanel doktorBilgileriAltPaneli;
    private javax.swing.JLabel doktorBilgileriAltPaneliBasligi;
    private javax.swing.JButton doktorBilgileriButonu;
    private javax.swing.JLabel doktorBilgileriButonuCizgisi;
    private javax.swing.JPanel doktorBilgileriPaneli;
    private javax.swing.JLabel doktorCinsiyetiBasligi;
    private javax.swing.JLabel doktorCinsiyetiYazisi;
    private javax.swing.JLabel doktorKimligiBasligi;
    private javax.swing.JLabel doktorKimligiYazisi;
    private javax.swing.JLabel doktorYasiBasligi;
    private javax.swing.JLabel doktorYasiYazisi;
    private javax.swing.JLabel erkekSayisi;
    private javax.swing.JLabel erkekSayisi1;
    private javax.swing.JButton girisButonu;
    private javax.swing.JPanel girisPaneli;
    private javax.swing.JPanel hastaDuzenleAltPaneli;
    private javax.swing.JButton hastaDuzenleButonu;
    private javax.swing.JPanel hastaEkleAltPaneli;
    private javax.swing.JButton hastaEkleButonu;
    private javax.swing.JLabel hastaIslemiAltPaneliBasligi;
    private javax.swing.JPanel hastaIslemleriAltPaneli;
    private javax.swing.JLabel hastaIslemleriAltPaneliBasligi;
    private javax.swing.JButton hastaIslemleriButonu;
    private javax.swing.JLabel hastaIslemleriButonuCizgisi;
    private javax.swing.JPanel hastaIslemleriPaneli;
    private javax.swing.JPanel hastaSilAltPaneli;
    private javax.swing.JButton hastaSilButonu;
    private javax.swing.JPanel hastaSorgulaAltPaneli;
    private javax.swing.JButton hastaSorgulaButonu;
    private javax.swing.JLabel hastaninAdiSoyadiBasligi;
    private javax.swing.JLabel hastaninAdiSoyadiDuzenleBasligi;
    private javax.swing.JTextField hastaninAdiSoyadiDuzenleVeriGirisi;
    private javax.swing.JTextField hastaninAdiSoyadiVeriGirisi;
    private javax.swing.JLabel hastaninCinsiyetiBasligi;
    private javax.swing.JLabel hastaninCinsiyetiDuzenleBasligi;
    private javax.swing.JTextField hastaninCinsiyetiDuzenleVeriGirisi;
    private javax.swing.JTextField hastaninCinsiyetiVeriGirisi;
    private javax.swing.JLabel hastaninDogumTarihiBasligi;
    private javax.swing.JLabel hastaninDogumTarihiDuzenleBasligi;
    private javax.swing.JTextField hastaninDogumTarihiDuzenleVeriGirisi;
    private javax.swing.JTextField hastaninDogumTarihiVeriGirisi;
    private javax.swing.JLabel hastaninDurumuBasligi;
    private javax.swing.JLabel hastaninDurumuDuzenleBasligi;
    private javax.swing.JTextField hastaninDurumuDuzenleVeriGirisi;
    private javax.swing.JTextField hastaninDurumuVeriGirisi;
    private javax.swing.JLabel hastaninHastaligiBasligi;
    private javax.swing.JLabel hastaninHastaligiDuzenleBasligi;
    private javax.swing.JTextField hastaninHastaligiDuzenleVeriGirisi;
    private javax.swing.JTextField hastaninHastaligiVeriGirisi;
    private javax.swing.JLabel hastaninTCKimligiBasligi;
    private javax.swing.JLabel hastaninTCKimligiDuzenleBasligi;
    private javax.swing.JTextField hastaninTCKimligiDuzenleVeriGirisi;
    private javax.swing.JLabel hastaninTCKimligiSilBasligi;
    private javax.swing.JTextField hastaninTCKimligiSilVeriGirisi;
    private javax.swing.JLabel hastaninTCKimligiSorgulaBasligi;
    private javax.swing.JTextField hastaninTCKimligiSorgulaVeriGirisi;
    private javax.swing.JTextField hastaninTCKimligiVeriGirisi;
    private javax.swing.JButton hastayiEkleButonu;
    private javax.swing.JButton hastayiKaydetButonu;
    private javax.swing.JButton hastayiSilButonu;
    private javax.swing.JButton hastayiSorgulaBuyonu;
    private javax.swing.JLabel kadinSayisi;
    private javax.swing.JLabel kadinSayisi1;
    private javax.swing.JScrollPane kayitliHastalarAltPaneli;
    private javax.swing.JLabel kayitliHastalarAltPaneliBasligi;
    private javax.swing.JList<String> kayitliHastalarListesi;
    private javax.swing.JLabel kisiSayisi;
    private javax.swing.JLabel kullaniciAdiBasligi;
    private javax.swing.JTextField kullaniciAdiVeriGirisi;
    private javax.swing.JPanel navigasyonPaneli;
    private javax.swing.JLabel sifreBasligi;
    private javax.swing.JPasswordField sifreVeriGirisi;
    private javax.swing.JLabel yasOrtalamasi;
    private javax.swing.JPanel yasOrtalamasiAltPaneli;
    private javax.swing.JLabel yasOrtalamasiAltPaneliBasligi;
    // End of variables declaration//GEN-END:variables
}
